# Generated by Django 4.1.7 on 2023-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_response',
            field=models.IntegerField(default=0),
        ),
    ]
