# Generated by Django 4.1.7 on 2023-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_profile_total_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_question',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
