# Generated by Django 4.1.7 on 2023-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_profile_business_question_profile_personal_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_question',
            field=models.CharField(default='Did myy business serve you well, please let me know', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_question',
            field=models.CharField(default='What exactly do you like about me', max_length=200),
        ),
    ]
