# Generated by Django 4.1.7 on 2023-04-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_alter_profile_business_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='business_question',
            field=models.CharField(default='Did my business serve you well, please let me know', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='personal_question',
            field=models.CharField(default='What exactly do you like about me', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_question',
            field=models.CharField(default='Did my business serve you well, please let me know', max_length=200),
        ),
    ]
