# Generated by Django 4.1.7 on 2023-04-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_message_business_question_message_personal_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homePage', models.IntegerField(default=0, editable=False, verbose_name='Home Page views')),
                ('contact_admin', models.IntegerField(default=0, editable=False, verbose_name='Contact admin views')),
                ('profile', models.IntegerField(default=0, editable=False, verbose_name='profile')),
                ('privacy_policy', models.IntegerField(default=0, editable=False, verbose_name='privacy policy views')),
                ('personal_quest_edit', models.IntegerField(default=0, editable=False, verbose_name='Number of personal question edits')),
                ('business_quest_edit', models.IntegerField(default=0, editable=False, verbose_name='Number of business question edits')),
                ('period', models.CharField(blank=True, editable=False, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Website Statistics',
            },
        ),
    ]
